### PR TITLE
Separate tasks for release and development images creation

### PR DESCRIPTION
**Pull request by fjammes**
Hi @jhoblitt , I've merge container construction code on Qserv side, could you please merge this PR which is tied to the same feature?

### CODE REVIEW

**Comment by fjammes** [comment]
Hi @jhoblitt , could you merge it please?

**Comment by jhoblitt** [comment]
Splitting the script into separate dev/release pipelines seems reasonable.  However, a "job" is still needed to execute the script.  The current job running the pipeline is: https://github.com/lsst-sqre/jenkins-dm-jobs/blob/master/jobs/qserv_docker_build.groovy#L28 Which will break because of the renaming of the existing pipeline.  There is a bit more complexity in that another job/pipeline has been triggering the `qserv/docker/build` job once a week.  I'm happy to fix all that up but I need to know what cadence you want to run the two new pipelines on.

**Comment by fjammes** [comment]
release should be built monthly (around the 7th), and qserv/qserv:dev should be built each week (manual build should also be available for both of them).

**Comment by fjammes** [comment]
Hi @jhoblitt , any chance for merging it please?

**Pull request closed without merging**
